# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.3
script:
- TEST_CMD="xcodebuild -scheme MoyaSwiftyJSONMapper -project MoyaSwiftyJSONMapper.xcodeproj  -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.1' build test" | xcpretty  && exit ${PIPESTATUS[0]}
after_success:
  - bash <(curl -s https://codecov.io/bash)
