language: objective-c
osx_image: xcode8
podfile: Example/Podfile
notifications:
  email: false
before_install: 
- gem uninstall cocoapods -a
- gem install cocoapods --pre
#- gem install bundler
#- bundle install
script:
#- bundle exec fastlane travis
#  - xcodebuild -workspace Postal.xcworkspace -scheme Postal-iOS -sdk iphonesimulator build
- xcodebuild test -workspace Example/Moya-SwiftyJSONMapper.xcworkspace -scheme Moya-SwiftyJSONMapper-Example -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0'
#after_success:
#  - bash <(curl -s https://codecov.io/bash)
